### ISSUE TITLE
Have a small description for licenses

### ISSUE THREAD

**Issue by vbajs** [memelicensesarchive/mla-main#3]
I propose that maybe we add a little description for each license whenever possible

An example would be for the Yes license, in which it would have the following description

"Yes license: An extremely condensed and shortened form of WTFPL!"

**Comment by MoltenCoreDev** [comment]
A lot of writing but cool.

**Comment by kreat0** [comment]
Alright, ill make it

**Comment by vbajs** [comment]
> 
> 
> A lot of writing but cool.

Not necessarily
An example would be the No license
"no"

**Comment by kreat0** [comment]
Done.

**Comment by vbajs** [comment]
20 WPM go vroooooooooo
